language: bash
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats git
  - sudo curl -fsSL -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.13.1/bin/linux/amd64/kubectl
  - sudo chmod +x /usr/bin/kubectl
  - sudo git clone https://github.com/capitalone/bash_shell_mock.git
  - cd bash_shell_mock
  - sudo ./install.sh /usr/local
  - cd -
script:
  - basename /usr/bin
  - bats tests/kubeio.bats

