language: bash
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats git libcurl4-openssl-dev libelf-dev libdw-dev cmake
  - sudo curl -fsSL -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.13.1/bin/linux/amd64/kubectl
  - sudo chmod +x /usr/bin/kubectl
  - sudo git clone https://github.com/capitalone/bash_shell_mock.git
  - cd bash_shell_mock
  - sudo ./install.sh /usr/local
  - cd -
  - sudo wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
  - sudo tar xzf master.tar.gz
  - cd kcov-master
  - sudo mkdir build
  - cd build
  - sudo cmake ..
  - sudo make
  - sudo make install
  - cd ../..
  - sudo rm -rf kcov-master
  - mkdir -p coverage
script:
  - basename /usr/bin
  - bats --tap tests/
after_success:
  - bash <(curl -s https://codecov.io/bash) -s coverage_install
  - bash <(curl -s https://codecov.io/bash) -s coverage_kubeio
